// This file was generated by the XState CLI, please do not edit it manually.
import { createMachine } from 'xstate';

const machine = createMachine(
  {
    context: {
      stars: 0,
    },
    id: 'Sleep',
    states: {
      Sound: {
        description: 'Sound is local to the user.',
        initial: 'Off',
        states: {
          Off: {
            on: {
              'toggle sound': {
                target: 'On',
              },
            },
          },
          On: {
            on: {
              'toggle sound': {
                target: 'Off',
              },
            },
          },
        },
      },
      Stars: {
        description: 'Stars are shared for all users.',
        initial: 'Idle',
        states: {
          Idle: {
            on: {
              'User joined': {
                target: 'Active session',
              },
            },
          },
          'Active session': {
            on: {
              'User left': {
                target: 'Idle',
              },
            },
          },
        },
      },
    },
    type: 'parallel',
    types: {
      events: {} as
        | { type: 'User left' }
        | { type: 'User joined' }
        | { type: 'toggle sound' },
      context: {} as { stars: number },
    },
  },
  {
    actions: {},
    actors: {},
    guards: {},
    delays: {},
  },
);
export const skyConfig = {
  actorId: 'abe111f9-4fcf-4c7b-9daa-42647db5520e',
  machine,
};
