// This file was generated by the XState CLI, please do not edit it manually.
import { createMachine } from 'xstate';

const machine = createMachine(
  {
    context: {
      stars: 0,
    },
    id: 'Sleep',
    states: {
      Sound: {
        initial: 'Off',
        states: {
          Off: {
            on: {
              'toggle sound': {
                target: 'On',
              },
            },
          },
          On: {
            on: {
              'toggle sound': {
                target: 'Off',
              },
            },
          },
        },
      },
      Colour: {
        initial: 'Black',
        states: {
          Black: {
            on: {
              'toggle colour': {
                target: 'Purple',
              },
            },
          },
          Purple: {
            on: {
              'toggle colour': {
                target: 'Blue',
              },
            },
          },
          Blue: {
            on: {
              'toggle colour': {
                target: 'Black',
              },
            },
          },
        },
      },
    },
    type: 'parallel',
    types: {
      events: {} as { type: 'toggle sound' } | { type: 'toggle colour' },
      context: {} as { stars: number },
    },
  },
  {
    actions: {},
    actors: {},
    guards: {},
    delays: {},
  },
);
export const skyConfig = {
  actorId: 'ea6d8903-6e06-4e7c-a51e-70fad496419b',
  machine,
};
